# Generated by Django 2.1.7 on 2019-04-03 07:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.IntegerField(default=10000, primary_key=True, serialize=False, unique=True)),
                ('board', jsonfield.fields.JSONField()),
            ],
        ),
    ]
