# Generated by Django 2.1.7 on 2019-04-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='id',
            field=models.AutoField(default=10000, primary_key=True, serialize=False, unique=True),
        ),
    ]
