# Generated by Django 2.1.7 on 2019-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190403_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
